### ISSUE TITLE
Custom data error

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-server-php#14]
Good day! This one not working

`	$chatkit->createUser(
		"user_login",
		"display_name",
		array(
	    "mymail" => "hello@hello.hello"
	  )
	);`

If i delete array its working

**Comment by alexey13** [comment]
Problem appear because i not used avatar url before custom data

**Comment by hamchapman** [comment]
Thanks for the issue report - we should add some validation to the parameter types to make this sort of thing impossible to hit.

**Comment by hamchapman** [comment]
This should be fixed by the fact that `createUser` now accepts an associative array 👍
