### ISSUE TITLE
getUserRooms crashes if optional 'joinable' option not set

### ISSUE THREAD

**Issue by mvrska** [pusher/chatkit-server-php#16]
### What?
see title

### Suggested improvements

change `is_null` function in getUserRooms to `isset`  on `L292`
from
```
$queryParams = is_null($options['joinable']) ? [] : ['joinable' => $options['joinable']];
```
to
```
$queryParams = isset($options['joinable']) : ['joinable' => $options['joinable']] :  [] ;
```

**Comment by hamchapman** [comment]
This is fixed in the latest release, [0.5.1](https://github.com/pusher/chatkit-server-php/blob/master/CHANGELOG.md#051---2018-05-25)

Thanks for the report!
