### ISSUE TITLE
user_id is expected to be string and causes a 'Could not parse the token' response if integer passed instead

### ISSUE THREAD

**Issue by mvrska** [pusher/chatkit-server-php#17]
### What?
see title

### Suggested improvements
a] validate the incoming user_id to be string and throw a reasonable exception 
or 
b] strval() it.

**Comment by hamchapman** [comment]
This is fixed in the latest release, [0.5.1](https://github.com/pusher/chatkit-server-php/blob/master/CHANGELOG.md#051---2018-05-25)

Thanks for the report!
