### ISSUE TITLE
Get room by user ids

### ISSUE THREAD

**Issue by nzkozar** [pusher/chatkit-server-php#50]
### What?
I'm looking for a way to retrieve a list of rooms which contain certain users.
I'm looking for something like the following:

`$chatkit->getRooms(['user_id1','user_id2']);`

which would return a list of all rooms that these two users are both members of.
Ideally the getRooms method would also have an optional parameter that would specify if returned rooms should only contain the provided users or also others.

Is this possible?

### Suggested improvements
 If not, is it something that can be added in the following release?

**Comment by syrsly** [comment]
It's not difficult to contain a list of all rooms and their users locally and simply use Pusher for the actual communication messages. Not sure if you thought of that yet, but thought I'd point it out as an option.

**Comment by jonathanlloyd** [comment]
Hi! Thanks for the feedback - if this still an issue for you could you send more details about your use case to support@pusher.com
