### ISSUE TITLE
Can't create user because it exists, then can't update same user because it doesn't exist

### ISSUE THREAD

**Issue by rickmacgillis** [pusher/chatkit-server-php#56]
### What?
I tried to create a user with this SDK, and it says it exists. So, the same method then tries to update the user instead, and the API says it DOESN'T exist.

Here's what the SDK is sending to create the user.

```
array:4 [
  "method" => "POST"
  "path" => "/users"
  "jwt" => "[REDACTED]"
  "body" => array:4 [
    "id" => "1"
    "name" => "Alejandra Bergnaum"
    "avatar_url" => "https://www.gravatar.com/avatar/5cc22172821c12cd0c014ed7af99ae6f.jpg?s=200&d=mm"
    "custom_data" => array:1 [
      "company" => "Romaguera-Bechtelar"
    ]
  ]
]
```
Response: `Chatkit\Exceptions\ChatkitException: User with given id already exists`

Here's what it sends to update the user once it catches the exception:

```
array:4 [
  "method" => "PUT"
  "path" => "/users/1"
  "jwt" => "[REDACTED]"
  "body" => array:3 [
    "name" => "Alejandra Bergnaum"
    "avatar_url" => "https://www.gravatar.com/avatar/5cc22172821c12cd0c014ed7af99ae6f.jpg?s=200&d=mm"
    "custom_data" => array:1 [
      "company" => "Romaguera-Bechtelar"
    ]
  ]
]
```
Response: `Chatkit\Exceptions\ChatkitException: The requested user does not exist`

### Suggested improvements

Given that the user cannot exist and not exist at the same time, you'll want to unify the code that's trying to locate the user. That way they both can find the user when it exists, but not when it doesn't.

**Comment by jonathanlloyd** [comment]
Hi thanks for the feedback!
This looks like an issue with the server-side deletion functionality rather than this SDK.
We've added a redesign of user deletion to our product roadmap.
Closing for this repo, but if you have any more questions on the progress of user deletion improvements please contact support@pusher.com
