### ISSUE TITLE
Restore a user?

### ISSUE THREAD

**Issue by d-thompson** [pusher/chatkit-server-php#68]
### What?
Once you have marked a user as deleted, shouldn't there be a way to mark the user as undeleted?
If I run `getUsersByID` it shows the user as existing but with a `deleted_at` time, but if I try to run `updateUser` it says that the user doesn't exist. The messages is possibly related to the issue: https://github.com/pusher/chatkit-server-php/issues/56 But surely as the existence of `deleted_at` suggests that you are following a soft delete type format, then you should be able to restore that user.

### Suggested improvements
Add a function that allows the restoration of a soft deleted user.
Or when you update a soft deleted user, rather than replying with `The requested user does not exist`, it removes the `deleted_at` data, and restores said user.

**Comment by jonathanlloyd** [comment]
Thanks for the feedback! I have added this to our product backlog.
