### ISSUE TITLE
OpenSSL SSL_read Issue with Curl calls

### ISSUE THREAD

**Issue by shellprog** [pusher/chatkit-server-php#69]
### What?
I have integrated chatkit server php for my help desk application. I am trying to execute multiple methods one by one as below

```
$this->chatKit->createRoom(...);
$this->chatKit->getUsersByID(...);
$this->chatKit->addUsersToRoom(...);
$this->chatKit->sendSimpleMessage(...);
$this->chatKit->getRoomMessages(...);
```

Everytime i try to access the api, the chatkit fails after some random method is executed, like it may fail after addUsersToRoom or for getRoomMessages. Following are some errors messages which i am receiving, message is random from below two.

1. OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0

2. OpenSSL SSL_read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0

**Environment**
Windows 10
OpenSSL 1.1.0g  2 Nov 2017
Chatkit version 1.9

Excerpt of StackTrace
```
[2020-03-06 07:06:30] local.ERROR: OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0 {"exception":"[object] (Chatkit\\Exceptions\\ConnectionException(code: 0): OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0 at D:\\Code\\help-desk\\vendor\\pusher\\pusher-chatkit-server\\src\\Chatkit.php:1473)
[stacktrace]
#0 D:\\Code\\help-desk\\vendor\\pusher\\pusher-chatkit-server\\src\\Chatkit.php(1134): Chatkit\\Chatkit->execCurl(Resource id #432)
#1 D:\\Code\\help-desk\\vendor\\pusher\\pusher-chatkit-server\\src\\Chatkit.php(1103): Chatkit\\Chatkit->makeRequest(Array, Array)
#2 D:\\Code\\help-desk\\vendor\\pusher\\pusher-chatkit-server\\src\\Chatkit.php(614): Chatkit\\Chatkit->apiRequestV2(Array)
```

Help is highly appreciated

**Comment by jonathanlloyd** [comment]
Hi! This looks like an issue with your cURL installation rather than the SDK itself - could you send a message to support@pusher.com and we'll help you debug. Thanks!
