### ISSUE TITLE
Cannot create room using createRoom API

### ISSUE THREAD

**Issue by luqmanrom** [pusher/chatkit-server-php#8]
I tried using createRoom API for this library, but I constantly getting this issue. I am pretty sure my instance locator and my key is fine since I manage to call another API successfully without any error. 

```
[
     "body" => "{"error":"authentication/jwt/invalid","error_description":"Could not parse the token"}",
     "status" => 401,
]

```

**Comment by hamchapman** [comment]
Which version are you using? I just tested with the latest version (0.2.1) and it worked as expected. 

If you're using 0.2.1 then please could you share one of JWTs that you're generating as part of the `createRoom` call? You can send it to me at hamilton@pusher.com

**Comment by luqmanrom** [comment]
@hamchapman Sent it. Thanks!

**Comment by luqmanrom** [comment]
Resolved in the email. My issue was, the user id I passed is an integer, but apparently it expects it to be a string. A better error message to reflect the real issues would be great.

Thanks @hamchapman

**Comment by scarletks1214** [comment]
I have some issues in creating a user in pusher by API, not node SDK.

I'd like to know how to get token (Bearer ****I can't get this ***) to send request API.
Hope to get your quick response.
Regards
